# Add this layer to BBPATH
BBPATH .= ":${LAYERDIR}"

# Tell BitBake where recipes and bbappends are located
BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "autonomouscar"
BBFILE_PATTERN_autonomouscar = "^${LAYERDIR}/"
BBFILE_PRIORITY_autonomouscar = "6"

# This layer depends on OpenEmbedded Core
LAYERDEPENDS_autonomouscar = "core"

# Your OpenSTLinux release is Scarthgap
LAYERSERIES_COMPAT_autonomouscar = "scarthgap"

AUTONOMOUS_CAR_SRC_ROOT = "/home/vmulay/embedded_projects/embedded_linux_labs"